baseURL = "https://themartes.com/"
languageCode = "en-us"
title = "TheMartes"
theme = "coder"

[params] # theme parameters
    author = "Matej Bunček" # author's name
    info = "Full Stack Developer" # author's job title or info
    description = "John Doe's personal website" # site description
    keywords = "blog,developer,personal" # site keywords
    
# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/TheMartes/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/TheMartes_/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/themartes/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "Stack"
    weight = 2
    url = "/stack/"
